In [226]:
import pandas as pd

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [227]:
import sys

sys.stdin.encoding
sys.stdout.encoding

'UTF-8'

In [228]:
data = pd.read_csv("/home/inns-sw/Thummim/datasets/tcpSYNflood5m-1h.csv", encoding="CP949")
# print(data.Source)
data = data[["No.", "Time", "Source", "Destination", "Protocol", "Length", "Info"]]
data

/home/inns-sw/anaconda3/envs/keras/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3049: DtypeWarning: Columns (11) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,No.,Time,Source,Destination,Protocol,Length,Info
0,1,0.000000,HewlettP_8e:40:b3,Spanning-tree-(for-bridges)_00,STP,64,RST. Root = 32768/0/00:18:6e:d7:8a:c0 Cost = ...
1,2,0.132712,AsustekC_64:40:79,Broadcast,ARP,60,Who has 172.27.224.250? Tell 172.27.224.251
2,3,0.134771,Telemech_09:51:3b,AsustekC_64:40:79,ARP,64,172.27.224.250 is at 00:80:f4:09:51:3b [ETHERN...
3,4,0.134788,172.27.224.251,172.27.224.250,TCP,60,50011 > 502 [SYN] Seq=0 Win=2048 Len=0 MSS=1460
4,5,0.144991,172.27.224.250,172.27.224.251,TCP,60,"502 > 50011 [SYN, ACK] Seq=0 Ack=1 Win=8192 ..."
...,...,...,...,...,...,...,...
92583,92584,3597.302263,172.27.224.250,172.27.224.251,TCP,60,502 > 50186 [ACK] Seq=1 Ack=7 Win=8712 Len=0
92584,92585,3597.311511,172.27.224.250,172.27.224.251,TCP,60,502 > 50186 [ACK] Seq=1 Ack=13 Win=8707 Len=0
92585,92586,3597.312342,172.27.224.250,172.27.224.251,Modbus/TCP,66,"Response: Trans: 1; Unit: 1, Func: 6: ..."
92586,92587,3597.514531,172.27.224.251,172.27.224.250,TCP,60,50186 > 502 [ACK] Seq=13 Ack=13 Win=2036 Len=0
92587,92588,3597.963734,HewlettP_8e:40:b3,Spanning-tree-(for-bridges)_00,STP,64,RST. Root = 32768/0/00:18:6e:d7:8a:c0 Cost = ...

In [229]:
data.columns
data = data.set_index(['Destination'])

In [230]:
label = []
for line in data["Time"]:
    if line >= 300 and line <= 600:
        label.append(1)
    else:
        label.append(0)
        

label = np.array(label)
data["label"] = label

data[data["label"] == 1]

,No.,Time,Source,Protocol,Length,Info,label
Destination,,,,,,,
172.27.224.250,3009,300.032271,250.161.98.95,TCP,174,2338 > 502 [SYN] Seq=0 Win=64 Len=120,1
172.27.224.250,3010,300.035922,113.195.57.129,TCP,174,2187 > 502 [SYN] Seq=0 Win=64 Len=120,1
172.27.224.250,3011,300.038421,172.27.224.251,TCP,60,"50114 > 502 [FIN, ACK] Seq=13 Ack=13 Win=203...",1
172.27.224.251,3012,300.048699,172.27.224.250,TCP,60,502 > 50114 [ACK] Seq=13 Ack=14 Win=8712 Len=0,1
172.27.224.251,3013,300.049526,172.27.224.250,TCP,60,"502 > 50114 [FIN, ACK] Seq=13 Ack=14 Win=871...",1
...,...,...,...,...,...,...,...
172.27.224.250,62643,599.952114,88.207.4.127,TCP,174,8349 > 502 [SYN] Seq=0 Win=64 Len=120,1
172.27.224.250,62644,599.955965,30.117.187.138,TCP,174,7831 > 502 [SYN] Seq=0 Win=64 Len=120,1
172.27.224.250,62645,599.958499,206.105.100.84,TCP,174,7859 > 502 [SYN] Seq=0 Win=64 Len=120,1
172.27.224.250,62646,599.958666,101.232.241.158,TCP,174,8119 > 502 [SYN] Seq=0 Win=64 Len=120,1
Spanning-tree-(for-bridges)_00,62647,599.993938,HewlettP_8e:40:b3,STP,64,RST. Root = 32768/0/00:18:6e:d7:8a:c0 Cost = ...,1

In [231]:
# 데이터 선처리

data = data.loc[data.index.isin(['172.27.224.250', '172.27.224.251'])]
len(data)
data

,No.,Time,Source,Protocol,Length,Info,label
Destination,,,,,,,
172.27.224.250,4,0.134788,172.27.224.251,TCP,60,50011 > 502 [SYN] Seq=0 Win=2048 Len=0 MSS=1460,0
172.27.224.251,5,0.144991,172.27.224.250,TCP,60,"502 > 50011 [SYN, ACK] Seq=0 Ack=1 Win=8192 ...",0
172.27.224.250,6,0.145009,172.27.224.251,TCP,60,50011 > 502 [ACK] Seq=1 Ack=1 Win=2048 Len=0,0
172.27.224.250,7,0.145452,172.27.224.251,TCP,60,"50011 > 502 [PSH, ACK] Seq=1 Ack=1 Win=2048 ...",0
172.27.224.250,8,0.145699,172.27.224.251,TCP,60,"50011 > 502 [PSH, ACK] Seq=2 Ack=1 Win=2048 ...",0
...,...,...,...,...,...,...,...
172.27.224.250,92583,3597.294184,172.27.224.251,TCP,60,"50186 > 502 [PSH, ACK] Seq=12 Ack=1 Win=2048...",0
172.27.224.251,92584,3597.302263,172.27.224.250,TCP,60,502 > 50186 [ACK] Seq=1 Ack=7 Win=8712 Len=0,0
172.27.224.251,92585,3597.311511,172.27.224.250,TCP,60,502 > 50186 [ACK] Seq=1 Ack=13 Win=8707 Len=0,0
172.27.224.251,92586,3597.312342,172.27.224.250,Modbus/TCP,66,"Response: Trans: 1; Unit: 1, Func: 6: ...",0
172.27.224.250,92587,3597.514531,172.27.224.251,TCP,60,50186 > 502 [ACK] Seq=13 Ack=13 Win=2036 Len=0,0

In [232]:
temp = []
for row in data.values:
    if row[3] == "TCP":
        temp.append(6)
    elif  "Modbus" in row[3] :
        temp.append(0)
    else:
        temp.append(-1)
data["Protocol"] = temp

In [234]:
data[data['label'] == 1]

,No.,Time,Source,Protocol,Length,Info,label
Destination,,,,,,,
172.27.224.250,3009,300.032271,250.161.98.95,6,174,2338 > 502 [SYN] Seq=0 Win=64 Len=120,1
172.27.224.250,3010,300.035922,113.195.57.129,6,174,2187 > 502 [SYN] Seq=0 Win=64 Len=120,1
172.27.224.250,3011,300.038421,172.27.224.251,6,60,"50114 > 502 [FIN, ACK] Seq=13 Ack=13 Win=203...",1
172.27.224.251,3012,300.048699,172.27.224.250,6,60,502 > 50114 [ACK] Seq=13 Ack=14 Win=8712 Len=0,1
172.27.224.251,3013,300.049526,172.27.224.250,6,60,"502 > 50114 [FIN, ACK] Seq=13 Ack=14 Win=871...",1
...,...,...,...,...,...,...,...
172.27.224.250,62642,599.951518,52.210.57.227,6,174,7100 > 502 [SYN] Seq=0 Win=64 Len=120,1
172.27.224.250,62643,599.952114,88.207.4.127,6,174,8349 > 502 [SYN] Seq=0 Win=64 Len=120,1
172.27.224.250,62644,599.955965,30.117.187.138,6,174,7831 > 502 [SYN] Seq=0 Win=64 Len=120,1
172.27.224.250,62645,599.958499,206.105.100.84,6,174,7859 > 502 [SYN] Seq=0 Win=64 Len=120,1
172.27.224.250,62646,599.958666,101.232.241.158,6,174,8119 > 502 [SYN] Seq=0 Win=64 Len=120,1

In [237]:
ivl = []
for i in range(0, len(data)):
    ivl.append(data["Time"][i+1] - data["Time"][i])
ivl

IndexError: index out of bounds

In [61]:
last = 0
interval = []
for pkt in data[data.index == "172.27.224.70"].values :
    if last == 0:
        last = pkt[1]
        interval.append(0)
    else:
        ivl = pkt[1] - last
        interval.append(ivl)
        last = pkt[1]
        
avg = sum(interval) / len(interval)

for ivl in interval:
    if ivl

SyntaxError: invalid syntax (<ipython-input-61-87bc846c450a>, line 15)